export const Mac = [
    {
        "id": 1,
        "img": "/shop/shop_mac.jpeg",
        "title": "MacBook Air 13,3  reconditionné avec puce Apple M1, GPU 7 cœurs et CPU 8 cœurs - Gris sidéral",
        "price": "1 349,00 €",
        "description":"noir | 128 GO | Bon état",
        MacInfo: {
            Model: 'MacBook Pro M1',
            Processor: 'Apple M1 chip',
            RAM: '8GB or 16GB unified memory',
            Storage: '256GB, 512GB, 1TB, or 2TB SSD',
            Display: '13.3-inch Retina display',
            Graphics: 'Apple 8-core GPU',
            Ports: '2 x Thunderbolt/USB 4 ports, 3.5mm headphone jack',
            OS: 'macOS Monterey',
        },
    },
    {
        "id": 2,
        "img": "/shop/shop_mac.jpeg",
        "title": "MacBook Pro 13,3  reconditionné avec puce Apple M1, GPU 7 cœurs et CPU 8 cœurs - Gris sidéral",
        "price": "2 349,00 €",
        "description":"noir | 128 GO | Bon état",
        MacInfo: {
            Model: 'MacBook Pro M1',
            Processor: 'Apple M1 chip',
            RAM: '8GB or 16GB unified memory',
            Storage: '256GB, 512GB, 1TB, or 2TB SSD',
            Display: '13.3-inch Retina display',
            Graphics: 'Apple 8-core GPU',
            Ports: '2 x Thunderbolt/USB 4 ports, 3.5mm headphone jack',
            OS: 'macOS Monterey',
        },
    },
    {
        "id": 3,
        "img": "/shop/shop_mac.jpeg",
        "title": "Imac 27,3  reconditionné avec puce Apple M1, GPU 7 cœurs et CPU 8 cœurs - Gris sidéral",
        "price": "349,00 €",
        "description":"noir | 128 GO | Bon état ",
        MacInfo: {
            Model: 'MacBook Pro M1',
            Processor: 'Apple M1 chip',
            RAM: '8GB or 16GB unified memory',
            Storage: '256GB, 512GB, 1TB, or 2TB SSD',
            Display: '13.3-inch Retina display',
            Graphics: 'Apple 8-core GPU',
            Ports: '2 x Thunderbolt/USB 4 ports, 3.5mm headphone jack',
            OS: 'macOS Monterey',
        },
    }, {
        "id": 4,
        "img": "/shop/shop_mac.jpeg",
        "title": "Imac 27,3  reconditionné avec puce Apple M1, GPU 7 cœurs et CPU 8 cœurs - Gris sidéral",
        "price": "349,00 €",
        "description":"noir | 128 GO | Bon état ",
        MacInfo: {
            Model: 'MacBook Pro M1',
            Processor: 'Apple M1 chip',
            RAM: '8GB or 16GB unified memory',
            Storage: '256GB, 512GB, 1TB, or 2TB SSD',
            Display: '13.3-inch Retina display',
            Graphics: 'Apple 8-core GPU',
            Ports: '2 x Thunderbolt/USB 4 ports, 3.5mm headphone jack',
            OS: 'macOS Monterey',
        },
    },
    {
        "id": 5,
        "img": "/shop/shop_mac.jpeg",
        "title": "Imac 27,3  reconditionné avec puce Apple M1, GPU 7 cœurs et CPU 8 cœurs - Gris sidéral",
        "price": "349,00 €",
        "description":"noir | 128 GO | Bon état ",
        MacInfo: {
            Model: 'MacBook Pro M1',
            Processor: 'Apple M1 chip',
            RAM: '8GB or 16GB unified memory',
            Storage: '256GB, 512GB, 1TB, or 2TB SSD',
            Display: '13.3-inch Retina display',
            Graphics: 'Apple 8-core GPU',
            Ports: '2 x Thunderbolt/USB 4 ports, 3.5mm headphone jack',
            OS: 'macOS Monterey',
        },
    },
    {
        "id": 5,
        "img": "/shop/shop_mac.jpeg",
        "title": "Imac 27,3  reconditionné avec puce Apple M1, GPU 7 cœurs et CPU 8 cœurs - Gris sidéral",
        "price": "349,00 €",
        "description":"noir | 128 GO | Bon état ",
        MacInfo: {
            Model: 'MacBook Pro M1',
            Processor: 'Apple M1 chip',
            RAM: '8GB or 16GB unified memory',
            Storage: '256GB, 512GB, 1TB, or 2TB SSD',
            Display: '13.3-inch Retina display',
            Graphics: 'Apple 8-core GPU',
            Ports: '2 x Thunderbolt/USB 4 ports, 3.5mm headphone jack',
            OS: 'macOS Monterey',
        },
    }
];